services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - pg-java
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://pg-java:5432/crypto
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - 8089:8089

  pg-java:
    image: 'postgres:13-alpine'
    container_name: pg-java
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=crypto
    volumes:
      - ./src/main/resources/sql/crypto_api.sql:/docker-entrypoint-initdb.d/crypto_api.sql
    ports:
      - "5433:5432"